# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d5795ef563c80f1c6b73676211bec6d9c1d9f963b0ee8591ce9b4df6bb1d323f3fb82ca76ae390fde48ae72b98a6b411c1328af92e5a19abce33d0a3e7f39d

test:
  secret_key_base: 39be3fc9a6f1fbec93d9c67bf81f5c432c31a795008c9d9c37bee1a507b4ab1831e0981881a6e9ee4af8b63fa6a378373aa4a9e4d24ee7178aa6b61bcadea2aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
